FROM php:8.3-cli

RUN apt-get update && apt-get install -y git zip unzip \
    && docker-php-ext-install pcntl bcmath sockets

COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
